In [2]:
from pathlib import Path
import numpy as np
import pprint

In [60]:
dest_folder = '/Users/shalu/Documents/ML-Research/data/test/Tiff_Tiles/7_Jul_2018_output_tiles/'
dest_folder2 = '/Users/shalu/Documents/ML-Research/data/keras-frcnn/test_images/'
filename = 'LC08_L1TP_040037_20180707_20180707_01_RT'

In [61]:
from skimage import  img_as_ubyte
from skimage import exposure
import rasterio

for i in range(15):
    for j in range(15):
        band2=dest_folder+filename+"_B2_window_{}_{}.tiff".format(i,j)
        band3=dest_folder+filename+"_B3_window_{}_{}.tiff".format(i,j)
        band4=dest_folder+filename+"_B4_window_{}_{}.tiff".format(i,j)
        band5=dest_folder+filename+"_B5_window_{}_{}.tiff".format(i,j)
        band6=dest_folder+filename+"_B6_window_{}_{}.tiff".format(i,j)
        band7=dest_folder+filename+"_B7_window_{}_{}.tiff".format(i,j)
        band10=dest_folder+filename+"_B10_window_{}_{}.tiff".format(i,j)
        with rasterio.open(band3) as b3_raster:
            b3_data = b3_raster.read(1)
#             transform=b3_raster.transform
#             crs=b3_raster.crs
#             profile=b3_raster.profile
        with rasterio.open(band2) as b2_raster:
            b2_data = b2_raster.read(1)
        with rasterio.open(band4) as b4_raster:
            b4_data = b4_raster.read(1)
        with rasterio.open(band5) as b5_raster:
            b5_data = b5_raster.read(1)
        with rasterio.open(band6) as b6_raster:
            b6_data = b6_raster.read(1)
        with rasterio.open(band7) as b7_raster:
            b7_data = b7_raster.read(1)
        with rasterio.open(band10) as b10_raster:
            b10_data = b10_raster.read(1)
            
        channels=np.empty([3,b3_data.shape[0],b3_data.shape[1]],dtype=np.uint8)

        for index,image in enumerate([b4_data,b7_data,b10_data]):
            stretched=exposure.equalize_hist(image)    
            channels[index,:,:] = img_as_ubyte(stretched)
            
        tif_filename = dest_folder2 / Path('LC08_L1TP_040037_20180707_20180707_01_RT_window_{}_{}.tiff'.format(i,j))
        num_chans, height, width = channels.shape
        with rasterio.open(tif_filename,'w',driver='GTiff',
                           height=height,width=width,
                           count=num_chans,dtype=channels.dtype,
                           crs=crs,transform=transform, nodata=0.0) as dst:
                dst.write(channels)
                keys=['4','7','10']
                for index,chan_name in enumerate(keys):
                    dst.update_tags(index+1,name=chan_name)
                    
        with rasterio.open(tif_filename) as infile:
            profile=infile.profile
            profile['driver']='JPEG'
            raster=infile.read()
            jpeg_filename=tif_filename.with_suffix('.jpeg')
            with rasterio.open(jpeg_filename, 'w', **profile) as dst:
                dst.write(raster)

W0512 09:40:05.442322 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option SHARING
W0512 09:40:05.458889 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option TILED
W0512 09:40:05.461332 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option INTERLEAVE
W0512 09:40:05.613389 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option SHARING
W0512 09:40:05.614650 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option TILED
W0512 09:40:05.615628 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option INTERLEAVE
W0512 09:40:05.799391 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option SHARI

W0512 09:40:08.231930 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option TILED
W0512 09:40:08.232547 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option INTERLEAVE
W0512 09:40:08.416283 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option SHARING
W0512 09:40:08.417130 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option TILED
W0512 09:40:08.417827 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option INTERLEAVE
W0512 09:40:08.602910 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option SHARING
W0512 09:40:08.603889 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option TILED

W0512 09:40:11.173168 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option INTERLEAVE
W0512 09:40:11.369249 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option SHARING
W0512 09:40:11.370247 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option TILED
W0512 09:40:11.370872 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option INTERLEAVE
W0512 09:40:11.549230 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option SHARING
W0512 09:40:11.550139 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option TILED
W0512 09:40:11.550886 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option INTER

W0512 09:40:14.637336 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option SHARING
W0512 09:40:14.638231 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option TILED
W0512 09:40:14.638955 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option INTERLEAVE
W0512 09:40:14.799877 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option SHARING
W0512 09:40:14.801258 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option TILED
W0512 09:40:14.802191 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option INTERLEAVE
W0512 09:40:14.908725 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option SHARI

W0512 09:40:17.808333 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option TILED
W0512 09:40:17.809545 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option INTERLEAVE
W0512 09:40:17.975115 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option SHARING
W0512 09:40:17.976042 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option TILED
W0512 09:40:17.976816 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option INTERLEAVE
W0512 09:40:18.162487 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option SHARING
W0512 09:40:18.163694 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option TILED

W0512 09:40:21.029899 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option INTERLEAVE
W0512 09:40:21.237518 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option SHARING
W0512 09:40:21.238503 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option TILED
W0512 09:40:21.239503 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option INTERLEAVE
W0512 09:40:21.417114 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option SHARING
W0512 09:40:21.418123 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option TILED
W0512 09:40:21.420518 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option INTER

W0512 09:40:24.396127 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option SHARING
W0512 09:40:24.397411 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option TILED
W0512 09:40:24.398179 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option INTERLEAVE
W0512 09:40:24.569844 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option SHARING
W0512 09:40:24.570694 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option TILED
W0512 09:40:24.571355 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option INTERLEAVE
W0512 09:40:24.727344 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option SHARI

W0512 09:40:27.427201 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option TILED
W0512 09:40:27.428158 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option INTERLEAVE
W0512 09:40:27.590184 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option SHARING
W0512 09:40:27.591065 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option TILED
W0512 09:40:27.591778 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option INTERLEAVE
W0512 09:40:27.740962 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option SHARING
W0512 09:40:27.742020 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option TILED

W0512 09:40:30.745594 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option INTERLEAVE
W0512 09:40:30.912439 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option SHARING
W0512 09:40:30.913466 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option TILED
W0512 09:40:30.914425 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option INTERLEAVE
W0512 09:40:31.088372 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option SHARING
W0512 09:40:31.089716 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option TILED
W0512 09:40:31.090523 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option INTER

W0512 09:40:34.172485 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option SHARING
W0512 09:40:34.173688 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option TILED
W0512 09:40:34.175225 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option INTERLEAVE
W0512 09:40:34.366511 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option SHARING
W0512 09:40:34.367718 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option TILED
W0512 09:40:34.368805 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option INTERLEAVE
W0512 09:40:34.567813 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option SHARI

W0512 09:40:37.361221 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option TILED
W0512 09:40:37.362071 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option INTERLEAVE
W0512 09:40:37.464298 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option SHARING
W0512 09:40:37.465250 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option TILED
W0512 09:40:37.465939 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option INTERLEAVE
W0512 09:40:37.569687 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option SHARING
W0512 09:40:37.570840 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option TILED

W0512 09:40:39.948013 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option INTERLEAVE
W0512 09:40:40.045001 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option SHARING
W0512 09:40:40.045866 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option TILED
W0512 09:40:40.046584 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option INTERLEAVE
W0512 09:40:40.140747 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option SHARING
W0512 09:40:40.142138 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option TILED
W0512 09:40:40.143290 4526220736 <ipython-input-61-4244f222bfc1>:55] CPLE_NotSupported in driver JPEG does not support creation option INTER

In [53]:
!python3 /Users/shalu/Documents/ML-Research/data/keras-frcnn/test_frcnn.py -p /Users/shalu/Documents/ML-Research/data/keras-frcnn/test_images

Using TensorFlow backend.
/Users/shalu/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/shalu/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/shalu/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/shalu/anaconda3/lib/python3.7/site-packages/tenso

Elapsed time = 6.894787788391113
[]
LC08_L1TP_040037_20180808_20180808_01_RT_window_0_5.jpeg
Elapsed time = 6.763364791870117
[]
LC08_L1TP_040037_20180808_20180808_01_RT_window_0_6.jpeg
Elapsed time = 6.785160303115845
[]
LC08_L1TP_040037_20180808_20180808_01_RT_window_0_7.jpeg
Elapsed time = 6.8912529945373535
[]
/Users/shalu/anaconda3/lib/python3.7/site-packages/skimage/io/_io.py:140: UserWarning: ./26.jpeg is a low contrast image
  warn('%s is a low contrast image' % fname)
LC08_L1TP_040037_20180808_20180808_01_RT_window_0_8.jpeg
Elapsed time = 7.855195999145508
[]
/Users/shalu/anaconda3/lib/python3.7/site-packages/skimage/io/_io.py:140: UserWarning: ./28.jpeg is a low contrast image
  warn('%s is a low contrast image' % fname)
LC08_L1TP_040037_20180808_20180808_01_RT_window_0_9.jpeg
Elapsed time = 7.727453947067261
[]
/Users/shalu/anaconda3/lib/python3.7/site-packages/skimage/io/_io.py:140: UserWarning: ./30.jpeg is a low contrast image
  warn('%s is a low contrast image' % fname)


Elapsed time = 8.46132493019104
[]
LC08_L1TP_040037_20180808_20180808_01_RT_window_13_9.jpeg
Elapsed time = 8.278011083602905
[]
LC08_L1TP_040037_20180808_20180808_01_RT_window_14_0.jpeg
Elapsed time = 8.995681047439575
[]
/Users/shalu/anaconda3/lib/python3.7/site-packages/skimage/io/_io.py:140: UserWarning: ./152.jpeg is a low contrast image
  warn('%s is a low contrast image' % fname)
LC08_L1TP_040037_20180808_20180808_01_RT_window_14_1.jpeg
Elapsed time = 9.235116958618164
[]
/Users/shalu/anaconda3/lib/python3.7/site-packages/skimage/io/_io.py:140: UserWarning: ./154.jpeg is a low contrast image
  warn('%s is a low contrast image' % fname)
LC08_L1TP_040037_20180808_20180808_01_RT_window_14_10.jpeg
Elapsed time = 8.433226823806763
[]
LC08_L1TP_040037_20180808_20180808_01_RT_window_14_11.jpeg
Elapsed time = 8.357140302658081
[]
LC08_L1TP_040037_20180808_20180808_01_RT_window_14_12.jpeg
Elapsed time = 8.595499038696289
[]
LC08_L1TP_040037_20180808_20180808_01_RT_window_14_13.jpeg
Elaps

Elapsed time = 8.791029930114746
[]
LC08_L1TP_040037_20180808_20180808_01_RT_window_3_3.jpeg
Elapsed time = 10.332199335098267
[]
LC08_L1TP_040037_20180808_20180808_01_RT_window_3_4.jpeg
Elapsed time = 10.260065078735352
[]
LC08_L1TP_040037_20180808_20180808_01_RT_window_3_5.jpeg
Elapsed time = 10.309308290481567
[('Fire', 99.99920129776001), ('Smoke', 99.91590976715088)]
LC08_L1TP_040037_20180808_20180808_01_RT_window_3_6.jpeg
Elapsed time = 10.101890802383423
[]
LC08_L1TP_040037_20180808_20180808_01_RT_window_3_7.jpeg
Elapsed time = 10.12191390991211
[]
LC08_L1TP_040037_20180808_20180808_01_RT_window_3_8.jpeg
Elapsed time = 10.158850193023682
[]
LC08_L1TP_040037_20180808_20180808_01_RT_window_3_9.jpeg
Elapsed time = 10.274014949798584
[]
LC08_L1TP_040037_20180808_20180808_01_RT_window_4_0.jpeg
Elapsed time = 9.183459997177124
[]
/Users/shalu/anaconda3/lib/python3.7/site-packages/skimage/io/_io.py:140: UserWarning: ./272.jpeg is a low contrast image
  warn('%s is a low contrast image'

Elapsed time = 7.522248983383179
[]
LC08_L1TP_040037_20180808_20180808_01_RT_window_8_3.jpeg
Elapsed time = 7.643287897109985
[('Smoke', 87.62605786323547)]
LC08_L1TP_040037_20180808_20180808_01_RT_window_8_4.jpeg
Elapsed time = 7.559072017669678
[]
LC08_L1TP_040037_20180808_20180808_01_RT_window_8_5.jpeg
Elapsed time = 7.689108848571777
[]
LC08_L1TP_040037_20180808_20180808_01_RT_window_8_6.jpeg
Elapsed time = 7.591936111450195
[]
LC08_L1TP_040037_20180808_20180808_01_RT_window_8_7.jpeg
Elapsed time = 7.620872259140015
[]
LC08_L1TP_040037_20180808_20180808_01_RT_window_8_8.jpeg
Elapsed time = 7.676845073699951
[]
LC08_L1TP_040037_20180808_20180808_01_RT_window_8_9.jpeg
Elapsed time = 7.453974962234497
[]
LC08_L1TP_040037_20180808_20180808_01_RT_window_9_0.jpeg
Elapsed time = 7.672708749771118
[]
LC08_L1TP_040037_20180808_20180808_01_RT_window_9_1.jpeg
Elapsed time = 7.642428159713745
[]
LC08_L1TP_040037_20180808_20180808_01_RT_window_9_10.jpeg
Elapsed time = 7.473296880722046
[]
LC08_

In [3]:
import json
import pandas as pd

df_train = pd.DataFrame(columns=["filename","width","height","class","xmin","ymin","xmax","ymax", "image", "label"])
df_temp = pd.DataFrame(columns=["filename","width","height","class","xmin","ymin","xmax","ymax", "image", "label"])


json_folder = '/Users/shalu/Documents/ML-Research/data/keras-frcnn/train_json/'
for file1 in Path(json_folder). iterdir():
    with open(file1) as json_data:
        data = json.load(json_data)
        if data["shapes"]:
                shape = data["shapes"]
                for shapedict in shape:
                    j="min"
                    for i in shapedict['points']:

                        if type(i) is list and len(i) == 2:

                            df_temp["x"+j] = [i[0]]
                            df_temp["y"+j] = [i[1]]
                            j = "max"
                            df_temp["class"] = [shapedict["label"]]
                            if shapedict["label"] ==  "Urban Area":
                                df_temp["label"]  = 1
                            if shapedict["label"] ==  "Forest":
                                df_temp["label"]  = 2
                            if shapedict["label"] ==  "Mountain":
                                df_temp["label"]  = 3 
                            if shapedict["label"] ==  "Burned Area":
                                df_temp["label"]  = 4
                            if shapedict["label"] ==  "Fire":
                                df_temp["label"]  = 5
                            if shapedict["label"] ==  "Smoke":
                                df_temp["label"]  = 6
                            if shapedict["label"] ==  "No Fire":
                                df_temp["label"]  = 7

                    df_temp["filename"] = [file1]

                    df_temp["width"] = [data["imageWidth"] ]       
                    df_temp["height"] = [data["imageHeight"]]
                    df_temp["image"] = [data["imagePath"] ]

                    df_train = df_train.append(df_temp)
        else:
            df_temp["filename"] = [file1]
            df_temp["width"] = [data["imageWidth"] ]       
            df_temp["height"] = [data["imageHeight"]]
            df_temp["image"] = [data["imagePath"] ]   
            df_temp["xmin"] = [0]
            df_temp["ymin"] = [0]
            df_temp["xmax"] = [0 + data["imageWidth"] ]
            df_temp["ymax"] = [0 + data["imageHeight"]]
            df_temp["label"] = [3]
            df_temp["class"] = ["nofire"]

In [4]:
df_train.head(10)

filename width height  class xmin  \
0  /Users/shalu/Documents/ML-Research/data/keras-...   854    869   Fire  286   
0  /Users/shalu/Documents/ML-Research/data/keras-...   854    869  Smoke  306   
0  /Users/shalu/Documents/ML-Research/data/keras-...   854    869  Smoke  258   
0  /Users/shalu/Documents/ML-Research/data/keras-...   854    869   Fire  367   
0  /Users/shalu/Documents/ML-Research/data/keras-...   854    869   Fire  512   
0  /Users/shalu/Documents/ML-Research/data/keras-...   854    869   Fire  579   
0  /Users/shalu/Documents/ML-Research/data/keras-...   854    869   Fire  162   
0  /Users/shalu/Documents/ML-Research/data/keras-...   854    869   Fire  535   
0  /Users/shalu/Documents/ML-Research/data/keras-...   854    869  Smoke  586   
0  /Users/shalu/Documents/ML-Research/data/keras-...   854    869  Smoke  476   

  ymin xmax ymax                                          image label  
0  188  333  227  LC08_L1TP_040037_20180808_20180808_01_RT.jpeg     5  
0  146  334  176  LC08_L1TP_040037_20180808_20180808_01_RT.jpeg     6  
0  176  283  198  LC08_L1TP_040037_20180808_20180808_01_RT.jpeg     6  
0  394  479  480  LC08_L1TP_040037_20131216_20170307_01_T1.jpeg     5  
0  389  711  463  LC08_L1TP_040037_20131216_20170307_01_T1.jpeg     5  
0  155  648  207  LC08_L1TP_040037_20131216_20170307_01_T1.jpeg     5  
0  441  307  501  LC08_L1TP_040037_20131216_20170307_01_T1.jpeg     5  
0  496  565  581  LC08_L1TP_040037_20180707_20180707_01_RT.jpeg     5  
0  515  638  634  LC08_L1TP_040037_20180707_20180707_01_RT.jpeg     6  
0  169  526  231  LC08_L1TP_040037_20180707_20180707_01_RT.jpeg     6

In [5]:
df_train.to_csv(json_folder+"/annotations.csv", index = False)

In [6]:
!pwd

/Users/shalu/Documents/ML-Research/data/keras-frcnn


In [81]:
!python3 train_frcnn.py -o simple -p annotate.txt

Using TensorFlow backend.
/Users/shalu/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/shalu/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/shalu/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/shalu/anaconda3/lib/python3.7/site-packages/tenso

LC08_L1TP_040037_20180707_20180707_01_RT_window_9_11.jpeg
<class 'numpy.ndarray'> [[[155  99 100]
  [153  97  98]
  [151  95  96]
  ...
  [171 207 229]
  [161 196 224]
  [150 184 219]]

 [[157 103 101]
  [154 100 100]
  [150  94  95]
  ...
  [168 204 230]
  [155 189 224]
  [142 176 214]]

 [[158 107 104]
  [155 101  99]
  [149  95  93]
  ...
  [160 194 231]
  [140 173 216]
  [121 153 202]]

 ...

 [[254 204  45]
  [254 206  46]
  [255 207  45]
  ...
  [ 12  16 141]
  [ 12  16 141]
  [  9  13 138]]

 [[255 205  48]
  [255 205  46]
  [255 205  46]
  ...
  [ 13  17 142]
  [ 10  14 139]
  [  2   6 131]]

 [[255 206  50]
  [255 206  49]
  [254 204  45]
  ...
  [ 14  18 143]
  [  8  12 137]
  [  0   0 125]]]
LC08_L1TP_040037_20180808_20180808_01_RT_window_1_5.jpeg,76,365,331,511,Fire

LC08_L1TP_040037_20180808_20180808_01_RT_window_1_5.jpeg
<class 'numpy.ndarray'> [[[ 33 115 215]
  [ 43 110 201]
  [ 12  81 156]
  ...
  [139  42 111]
  [163  61 108]
  [167  63  98]]

 [[ 57 126 245]
  [ 60 11

LC08_L1TP_040037_20180707_20180707_01_RT_window_4_8.jpeg
<class 'numpy.ndarray'> [[[ 31  32 150]
  [ 31  31 151]
  [ 30  30 154]
  ...
  [207 189  31]
  [207 191  33]
  [207 194  36]]

 [[ 28  28 148]
  [ 27  27 149]
  [ 26  25 152]
  ...
  [201 185  27]
  [202 188  29]
  [202 190  30]]

 [[ 27  29 152]
  [ 26  27 153]
  [ 25  25 155]
  ...
  [198 184  23]
  [199 187  27]
  [198 188  28]]

 ...

 [[ 80  99  44]
  [ 76  95  40]
  [ 71  89  37]
  ...
  [148 182 210]
  [159 212 168]
  [151 216 136]]

 [[ 83 104  47]
  [ 78  99  42]
  [ 73  94  37]
  ...
  [131 164 195]
  [151 205 171]
  [153 214 155]]

 [[ 84 108  48]
  [ 80 101  42]
  [ 74  95  38]
  ...
  [111 144 177]
  [140 193 167]
  [151 210 166]]]
LC08_L1TP_040037_20180707_20180707_01_RT_window_4_8.jpeg,472,76,505,135,Fire

LC08_L1TP_040037_20180707_20180707_01_RT_window_4_8.jpeg,281,0,341,35,Fire

LC08_L1TP_040037_20180707_20180707_01_RT_window_4_8.jpeg,366,4,459,78,Smoke

LC08_L1TP_040037_20180707_20180707_01_RT_window_11_11.jpeg

50/50 [==============================] - 498s 10s/step - rpn_cls: 4.5716 - rpn_regr: 0.2671 - detector_cls: 0.6934 - detector_regr: 0.4914
Mean number of bounding boxes from RPN overlapping ground truth boxes: 5.0
Classifier accuracy for bounding boxes from RPN: 0.83
Loss RPN classifier: 4.571620353460312
Loss RPN regression: 0.2670975125581026
Loss Detector classifier: 0.6933560526371002
Loss Detector regression: 0.4913893796503544
Elapsed time: 497.7028729915619
Total loss decreased from inf to 6.023463298305869, saving weights
Epoch 2/50
Hello
Average number of overlapping bounding boxes from RPN = 5.0 for 50 previous iterations
Before data generation
 9/50 [====>.........................] - ETA: 6:42 - rpn_cls: 3.0506 - rpn_regr: 0.2578 - detector_cls: 0.5953 - detector_regr: 0.4115Before data generation


50/50 [==============================] - 502s 10s/step - rpn_cls: 2.3903 - rpn_regr: 0.2363 - detector_cls: 0.6780 - detector_regr: 0.4520
Mean number of bounding boxes from RPN overlapping ground truth boxes: 8.92
Classifier accuracy for bounding boxes from RPN: 0.723125
Loss RPN classifier: 2.3902632117271425
Loss RPN regression: 0.23628019634634256
Loss Detector classifier: 0.6780149871110916
Loss Detector regression: 0.4520154128968716
Elapsed time: 527.3187549114227
Total loss decreased from 6.023463298305869 to 3.7565738080814484, saving weights
Epoch 3/50
Hello
Average number of overlapping bounding boxes from RPN = 8.92 for 50 previous iterations
Before data generation
 8/50 [===>..........................] - ETA: 6:37 - rpn_cls: 1.2741 - rpn_regr: 0.2086 - detector_cls: 0.4490 - detector_regr: 0.4128Before data generation


50/50 [==============================] - 478s 10s/step - rpn_cls: 0.9759 - rpn_regr: 0.2263 - detector_cls: 0.5569 - detector_regr: 0.4386
Mean number of bounding boxes from RPN overlapping ground truth boxes: 8.24
Classifier accuracy for bounding boxes from RPN: 0.7425
Loss RPN classifier: 0.9759021412208676
Loss RPN regression: 0.22625613763928412
Loss Detector classifier: 0.5569201841950416
Loss Detector regression: 0.43855520240962503
Elapsed time: 479.1485049724579
Total loss decreased from 3.7565738080814484 to 2.1976336654648185, saving weights
Epoch 4/50
Hello
Average number of overlapping bounding boxes from RPN = 8.24 for 50 previous iterations
Before data generation
 7/50 [===>..........................] - ETA: 7:17 - rpn_cls: 0.7638 - rpn_regr: 0.1809 - detector_cls: 0.5635 - detector_regr: 0.4341Before data generation


50/50 [==============================] - 533s 11s/step - rpn_cls: 0.8305 - rpn_regr: 0.1834 - detector_cls: 0.5243 - detector_regr: 0.4269
Mean number of bounding boxes from RPN overlapping ground truth boxes: 10.02
Classifier accuracy for bounding boxes from RPN: 0.711875
Loss RPN classifier: 0.8305012707412243
Loss RPN regression: 0.18336226150393486
Loss Detector classifier: 0.5243029350042343
Loss Detector regression: 0.42692070484161376
Elapsed time: 533.926784992218
Total loss decreased from 2.1976336654648185 to 1.9650871720910073, saving weights
Epoch 5/50
Hello
Average number of overlapping bounding boxes from RPN = 10.02 for 50 previous iterations
Before data generation
 6/50 [==>...........................] - ETA: 7:34 - rpn_cls: 0.1887 - rpn_regr: 0.1981 - detector_cls: 0.5062 - detector_regr: 0.4518Before data generation


50/50 [==============================] - 536s 11s/step - rpn_cls: 0.5062 - rpn_regr: 0.1910 - detector_cls: 0.4938 - detector_regr: 0.4024
Mean number of bounding boxes from RPN overlapping ground truth boxes: 10.0
Classifier accuracy for bounding boxes from RPN: 0.765
Loss RPN classifier: 0.5062297934852541
Loss RPN regression: 0.19104020228609442
Loss Detector classifier: 0.4938440334796905
Loss Detector regression: 0.4023578605055809
Elapsed time: 536.7168910503387
Total loss decreased from 1.9650871720910073 to 1.59347188975662, saving weights
Epoch 6/50
Hello
Average number of overlapping bounding boxes from RPN = 10.0 for 50 previous iterations
Before data generation
 5/50 [==>...........................] - ETA: 7:45 - rpn_cls: 0.2019 - rpn_regr: 0.0890 - detector_cls: 0.2864 - detector_regr: 0.3416Before data generation


50/50 [==============================] - 497s 10s/step - rpn_cls: 0.3112 - rpn_regr: 0.1693 - detector_cls: 0.3612 - detector_regr: 0.3348
Mean number of bounding boxes from RPN overlapping ground truth boxes: 9.7
Classifier accuracy for bounding boxes from RPN: 0.83375
Loss RPN classifier: 0.31124088247306647
Loss RPN regression: 0.16931019810959697
Loss Detector classifier: 0.36123327299952507
Loss Detector regression: 0.33484718337655067
Elapsed time: 498.11871695518494
Total loss decreased from 1.59347188975662 to 1.1766315369587392, saving weights
Epoch 7/50
Hello
Average number of overlapping bounding boxes from RPN = 9.7 for 50 previous iterations
Before data generation
 4/50 [=>............................] - ETA: 7:21 - rpn_cls: 0.9538 - rpn_regr: 0.1284 - detector_cls: 0.5767 - detector_regr: 0.3648Before data generation


50/50 [==============================] - 491s 10s/step - rpn_cls: 0.3807 - rpn_regr: 0.1516 - detector_cls: 0.4121 - detector_regr: 0.3012
Mean number of bounding boxes from RPN overlapping ground truth boxes: 10.82
Classifier accuracy for bounding boxes from RPN: 0.818125
Loss RPN classifier: 0.38067544177174567
Loss RPN regression: 0.15157013028860092
Loss Detector classifier: 0.4121127524971962
Loss Detector regression: 0.3012490430474281
Elapsed time: 492.172532081604
Epoch 8/50
Hello
Average number of overlapping bounding boxes from RPN = 10.82 for 50 previous iterations
Before data generation
 4/50 [=>............................] - ETA: 10:00 - rpn_cls: 0.9294 - rpn_regr: 0.0719 - detector_cls: 0.4873 - detector_regr: 0.3205Before data generation


50/50 [==============================] - 508s 10s/step - rpn_cls: 0.3818 - rpn_regr: 0.1457 - detector_cls: 0.4489 - detector_regr: 0.3036
Mean number of bounding boxes from RPN overlapping ground truth boxes: 10.78
Classifier accuracy for bounding boxes from RPN: 0.78875
Loss RPN classifier: 0.38175123821943996
Loss RPN regression: 0.1456637951359153
Loss Detector classifier: 0.44891812160611155
Loss Detector regression: 0.3036186245083809
Elapsed time: 507.5101978778839
Epoch 9/50
Hello
Average number of overlapping bounding boxes from RPN = 10.78 for 50 previous iterations
Before data generation
 4/50 [=>............................] - ETA: 7:22 - rpn_cls: 0.0681 - rpn_regr: 0.1256 - detector_cls: 0.3432 - detector_regr: 0.2242Before data generation


50/50 [==============================] - 517s 10s/step - rpn_cls: 0.3273 - rpn_regr: 0.1281 - detector_cls: 0.3277 - detector_regr: 0.2546
Mean number of bounding boxes from RPN overlapping ground truth boxes: 10.94
Classifier accuracy for bounding boxes from RPN: 0.836875
Loss RPN classifier: 0.3272849817574024
Loss RPN regression: 0.12811942735221238
Loss Detector classifier: 0.3276500352472067
Loss Detector regression: 0.25458333767950536
Elapsed time: 516.961179971695
Total loss decreased from 1.1766315369587392 to 1.037637782036327, saving weights
Epoch 10/50
Hello
Average number of overlapping bounding boxes from RPN = 10.94 for 50 previous iterations
Before data generation
 3/50 [>.............................] - ETA: 7:47 - rpn_cls: 0.0105 - rpn_regr: 0.0234 - detector_cls: 0.2450 - detector_regr: 0.1738Before data generation


50/50 [==============================] - 519s 10s/step - rpn_cls: 0.2683 - rpn_regr: 0.1157 - detector_cls: 0.2612 - detector_regr: 0.2265
Mean number of bounding boxes from RPN overlapping ground truth boxes: 11.52
Classifier accuracy for bounding boxes from RPN: 0.89625
Loss RPN classifier: 0.2683167063537985
Loss RPN regression: 0.11568340983707458
Loss Detector classifier: 0.26115025140345094
Loss Detector regression: 0.22647931322455406
Elapsed time: 520.3429720401764
Total loss decreased from 1.037637782036327 to 0.871629680818878, saving weights
Epoch 11/50
Hello
Average number of overlapping bounding boxes from RPN = 11.52 for 50 previous iterations
Before data generation
 2/50 [>.............................] - ETA: 8:38 - rpn_cls: 0.1067 - rpn_regr: 0.2073 - detector_cls: 0.5064 - detector_regr: 0.3008Before data generation


50/50 [==============================] - 532s 11s/step - rpn_cls: 0.2914 - rpn_regr: 0.1136 - detector_cls: 0.2624 - detector_regr: 0.2723
Mean number of bounding boxes from RPN overlapping ground truth boxes: 11.56
Classifier accuracy for bounding boxes from RPN: 0.898125
Loss RPN classifier: 0.29136824698187413
Loss RPN regression: 0.11357374045066536
Loss Detector classifier: 0.2623892666399479
Loss Detector regression: 0.27229212686419485
Elapsed time: 533.0023109912872
Epoch 12/50
Hello
Average number of overlapping bounding boxes from RPN = 11.56 for 50 previous iterations
Before data generation
 2/50 [>.............................] - ETA: 8:15 - rpn_cls: 0.0499 - rpn_regr: 0.0202 - detector_cls: 0.2599 - detector_regr: 0.2579    Before data generation


50/50 [==============================] - 527s 11s/step - rpn_cls: 0.2143 - rpn_regr: 0.1005 - detector_cls: 0.2387 - detector_regr: 0.2270
Mean number of bounding boxes from RPN overlapping ground truth boxes: 11.62
Classifier accuracy for bounding boxes from RPN: 0.904375
Loss RPN classifier: 0.21428567186463623
Loss RPN regression: 0.10054537339223316
Loss Detector classifier: 0.2386504500359297
Loss Detector regression: 0.2270234115421772
Elapsed time: 526.6755421161652
Total loss decreased from 0.871629680818878 to 0.7805049068349763, saving weights
Epoch 13/50
Hello
Average number of overlapping bounding boxes from RPN = 11.62 for 50 previous iterations
Before data generation
 1/50 [..............................] - ETA: 7:55 - rpn_cls: 3.0152 - rpn_regr: 0.0254 - detector_cls: 0.2445 - detector_regr: 0.2323Before data generation


50/50 [==============================] - 503s 10s/step - rpn_cls: 0.2798 - rpn_regr: 0.0886 - detector_cls: 0.2353 - detector_regr: 0.1938
Mean number of bounding boxes from RPN overlapping ground truth boxes: 11.58
Classifier accuracy for bounding boxes from RPN: 0.905
Loss RPN classifier: 0.2797887977724895
Loss RPN regression: 0.08857059778863913
Loss Detector classifier: 0.23526735164225102
Loss Detector regression: 0.19383404012769462
Elapsed time: 504.1145579814911
Epoch 14/50
Hello
Average number of overlapping bounding boxes from RPN = 11.58 for 50 previous iterations
Before data generation
 1/50 [..............................] - ETA: 7:59 - rpn_cls: 0.0193 - rpn_regr: 0.0239 - detector_cls: 0.2446 - detector_regr: 0.1014Before data generation


50/50 [==============================] - 480s 10s/step - rpn_cls: 0.2320 - rpn_regr: 0.0900 - detector_cls: 0.2260 - detector_regr: 0.1692
Mean number of bounding boxes from RPN overlapping ground truth boxes: 11.5
Classifier accuracy for bounding boxes from RPN: 0.9125
Loss RPN classifier: 0.2319583180360496
Loss RPN regression: 0.08998993000877817
Loss Detector classifier: 0.22596580862998963
Loss Detector regression: 0.16923288386315108
Elapsed time: 480.05978202819824
Total loss decreased from 0.7805049068349763 to 0.7171469405379685, saving weights
Epoch 15/50
Hello
Average number of overlapping bounding boxes from RPN = 11.5 for 50 previous iterations
Before data generation


50/50 [==============================] - 481s 10s/step - rpn_cls: 0.1494 - rpn_regr: 0.0795 - detector_cls: 0.2530 - detector_regr: 0.1725
Mean number of bounding boxes from RPN overlapping ground truth boxes: 10.86
Classifier accuracy for bounding boxes from RPN: 0.90125
Loss RPN classifier: 0.14940956943668426
Loss RPN regression: 0.0795258836573339
Loss Detector classifier: 0.2530374063551426
Loss Detector regression: 0.17252777103334666
Elapsed time: 481.91841101646423
Total loss decreased from 0.7171469405379685 to 0.6545006304825074, saving weights


Epoch 16/50
Hello
Average number of overlapping bounding boxes from RPN = 10.86 for 50 previous iterations
Before data generation
50/50 [==============================] - 481s 10s/step - rpn_cls: 0.2529 - rpn_regr: 0.0743 - detector_cls: 0.2331 - detector_regr: 0.1571
Mean number of bounding boxes from RPN overlapping ground truth boxes: 11.2
Classifier accuracy for bounding boxes from RPN: 0.901875
Loss RPN classifier: 0.2528551618894562
Loss RPN regression: 0.07434411250505946
Loss Detector classifier: 0.23308776214718818
Loss Detector regression: 0.1571130046248436
Elapsed time: 481.8380732536316
Epoch 17/50
Hello
Average number of overlapping bounding boxes from RPN = 11.2 for 50 previous iterations
Before data generation


50/50 [==============================] - 483s 10s/step - rpn_cls: 0.2662 - rpn_regr: 0.0616 - detector_cls: 0.2542 - detector_regr: 0.1524
Mean number of bounding boxes from RPN overlapping ground truth boxes: 11.22
Classifier accuracy for bounding boxes from RPN: 0.894375
Loss RPN classifier: 0.2662298214389011
Loss RPN regression: 0.061602105590900465
Loss Detector classifier: 0.25419885508716106
Loss Detector regression: 0.15237958334386348
Elapsed time: 482.65034008026123
Epoch 18/50
Hello
Average number of overlapping bounding boxes from RPN = 11.22 for 50 previous iterations
Before data generation


50/50 [==============================] - 479s 10s/step - rpn_cls: 0.2093 - rpn_regr: 0.0549 - detector_cls: 0.1362 - detector_regr: 0.1295
Mean number of bounding boxes from RPN overlapping ground truth boxes: 12.0
Classifier accuracy for bounding boxes from RPN: 0.953125
Loss RPN classifier: 0.20925114424433558
Loss RPN regression: 0.05486264550270789
Loss Detector classifier: 0.13619909960776566
Loss Detector regression: 0.12945676686242222
Elapsed time: 478.7904019355774
Total loss decreased from 0.6545006304825074 to 0.5297696562172314, saving weights


Epoch 19/50
Hello
Average number of overlapping bounding boxes from RPN = 12.0 for 50 previous iterations
Before data generation
50/50 [==============================] - 470s 9s/step - rpn_cls: 0.1973 - rpn_regr: 0.0477 - detector_cls: 0.1250 - detector_regr: 0.0962
Mean number of bounding boxes from RPN overlapping ground truth boxes: 11.6
Classifier accuracy for bounding boxes from RPN: 0.9625
Loss RPN classifier: 0.1972583399899304
Loss RPN regression: 0.047679102307156426
Loss Detector classifier: 0.12501383701339364
Loss Detector regression: 0.09616415055468679
Elapsed time: 471.22313809394836
Total loss decreased from 0.5297696562172314 to 0.46611542986516724, saving weights


Epoch 20/50
Hello
Average number of overlapping bounding boxes from RPN = 11.6 for 50 previous iterations
Before data generation
50/50 [==============================] - 476s 10s/step - rpn_cls: 0.1464 - rpn_regr: 0.0467 - detector_cls: 0.1209 - detector_regr: 0.0979
Mean number of bounding boxes from RPN overlapping ground truth boxes: 11.34
Classifier accuracy for bounding boxes from RPN: 0.955625
Loss RPN classifier: 0.14637863150332123
Loss RPN regression: 0.04672148804426797
Loss Detector classifier: 0.12088153561577202
Loss Detector regression: 0.09785792522132397
Elapsed time: 477.3173842430115
Total loss decreased from 0.46611542986516724 to 0.4118395803846852, saving weights


Epoch 21/50
Hello
Average number of overlapping bounding boxes from RPN = 11.34 for 50 previous iterations
Before data generation
50/50 [==============================] - 482s 10s/step - rpn_cls: 0.1947 - rpn_regr: 0.0378 - detector_cls: 0.1148 - detector_regr: 0.1068
Mean number of bounding boxes from RPN overlapping ground truth boxes: 12.48
Classifier accuracy for bounding boxes from RPN: 0.95625
Loss RPN classifier: 0.19468742442084477
Loss RPN regression: 0.03780639592223452
Loss Detector classifier: 0.11484467186033726
Loss Detector regression: 0.10683089189231396
Elapsed time: 483.284166097641
Epoch 22/50
Hello
Average number of overlapping bounding boxes from RPN = 12.48 for 50 previous iterations
Before data generation


50/50 [==============================] - 494s 10s/step - rpn_cls: 0.2152 - rpn_regr: 0.0381 - detector_cls: 0.1642 - detector_regr: 0.1269
Mean number of bounding boxes from RPN overlapping ground truth boxes: 11.54
Classifier accuracy for bounding boxes from RPN: 0.939375
Loss RPN classifier: 0.2151609171589371
Loss RPN regression: 0.03811997398464882
Loss Detector classifier: 0.16418602343648672
Loss Detector regression: 0.12685876913368702
Elapsed time: 493.54341220855713
Epoch 23/50
Hello
Average number of overlapping bounding boxes from RPN = 11.54 for 50 previous iterations
Before data generation


50/50 [==============================] - 487s 10s/step - rpn_cls: 0.2078 - rpn_regr: 0.0337 - detector_cls: 0.1666 - detector_regr: 0.0928
Mean number of bounding boxes from RPN overlapping ground truth boxes: 11.68
Classifier accuracy for bounding boxes from RPN: 0.936875
Loss RPN classifier: 0.20782201466383413
Loss RPN regression: 0.033695647421009195
Loss Detector classifier: 0.16655347988009453
Loss Detector regression: 0.09276383937336505
Elapsed time: 487.244017124176
Epoch 24/50
Hello
Average number of overlapping bounding boxes from RPN = 11.68 for 50 previous iterations
Before data generation


50/50 [==============================] - 497s 10s/step - rpn_cls: 0.1954 - rpn_regr: 0.0239 - detector_cls: 0.1557 - detector_regr: 0.0919
Mean number of bounding boxes from RPN overlapping ground truth boxes: 11.92
Classifier accuracy for bounding boxes from RPN: 0.939375
Loss RPN classifier: 0.1953596563579049
Loss RPN regression: 0.02393210725771496
Loss Detector classifier: 0.15572670068591832
Loss Detector regression: 0.09193061420693993
Elapsed time: 496.73484230041504
Epoch 25/50
Hello
Average number of overlapping bounding boxes from RPN = 11.92 for 50 previous iterations
Before data generation


50/50 [==============================] - 502s 10s/step - rpn_cls: 0.2020 - rpn_regr: 0.0300 - detector_cls: 0.1051 - detector_regr: 0.0852
Mean number of bounding boxes from RPN overlapping ground truth boxes: 11.46
Classifier accuracy for bounding boxes from RPN: 0.959375
Loss RPN classifier: 0.20196219676174224
Loss RPN regression: 0.02999312228832423
Loss Detector classifier: 0.10506387091241777
Loss Detector regression: 0.08521837500855327
Elapsed time: 501.58321714401245
Epoch 26/50
Hello
Average number of overlapping bounding boxes from RPN = 11.46 for 50 previous iterations
Before data generation


50/50 [==============================] - 482s 10s/step - rpn_cls: 0.1300 - rpn_regr: 0.0234 - detector_cls: 0.1112 - detector_regr: 0.0728
Mean number of bounding boxes from RPN overlapping ground truth boxes: 11.28
Classifier accuracy for bounding boxes from RPN: 0.95625
Loss RPN classifier: 0.13001731569936964
Loss RPN regression: 0.023436705447747955
Loss Detector classifier: 0.11124372829683125
Loss Detector regression: 0.0727532659471035
Elapsed time: 482.36207914352417
Total loss decreased from 0.4118395803846852 to 0.3374510153910524, saving weights


Epoch 27/50
Hello
Average number of overlapping bounding boxes from RPN = 11.28 for 50 previous iterations
Before data generation
50/50 [==============================] - 498s 10s/step - rpn_cls: 0.1949 - rpn_regr: 0.0171 - detector_cls: 0.0943 - detector_regr: 0.0684
Mean number of bounding boxes from RPN overlapping ground truth boxes: 12.0
Classifier accuracy for bounding boxes from RPN: 0.964375
Loss RPN classifier: 0.194916875656927
Loss RPN regression: 0.017147662476693314
Loss Detector classifier: 0.09434639823623002
Loss Detector regression: 0.06842417385429143
Elapsed time: 499.53140902519226
Epoch 28/50
Hello
Average number of overlapping bounding boxes from RPN = 12.0 for 50 previous iterations
Before data generation


12/50 [======>.......................] - ETA: 6:11 - rpn_cls: 0.2561 - rpn_regr: 0.0104 - detector_cls: 0.1552 - detector_regr: 0.0625Before data generation
^C


In [82]:
!python3 /Users/shalu/Documents/ML-Research/data/keras-frcnn/test_frcnn.py -p /Users/shalu/Documents/ML-Research/data/keras-frcnn/test_images

Using TensorFlow backend.
/Users/shalu/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/shalu/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/shalu/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/shalu/anaconda3/lib/python3.7/site-packages/tenso

LC08_L1TP_040037_20180707_20180707_01_RT_window_11_12.jpeg
Elapsed time = 7.278961896896362
[]
LC08_L1TP_040037_20180707_20180707_01_RT_window_11_2.jpeg
Elapsed time = 7.689793109893799
[]
LC08_L1TP_040037_20180707_20180707_01_RT_window_11_3.jpeg
Elapsed time = 7.19281792640686
[]
LC08_L1TP_040037_20180707_20180707_01_RT_window_11_4.jpeg
Elapsed time = 7.254566192626953
[]
LC08_L1TP_040037_20180707_20180707_01_RT_window_11_5.jpeg
Elapsed time = 7.105970859527588
[]
LC08_L1TP_040037_20180707_20180707_01_RT_window_11_6.jpeg
Elapsed time = 7.101985216140747
[]
LC08_L1TP_040037_20180707_20180707_01_RT_window_11_7.jpeg
Elapsed time = 7.157328844070435
[]
LC08_L1TP_040037_20180707_20180707_01_RT_window_11_8.jpeg
Elapsed time = 7.240262985229492
[]
LC08_L1TP_040037_20180707_20180707_01_RT_window_11_9.jpeg
Elapsed time = 7.103056907653809
[]
LC08_L1TP_040037_20180707_20180707_01_RT_window_12_0.jpeg
Elapsed time = 7.4539477825164795
[]
LC08_L1TP_040037_20180707_20180707_01_RT_window_12_1.jpeg
E

Elapsed time = 10.379156112670898
[]
LC08_L1TP_040037_20180707_20180707_01_RT_window_5_5.jpeg
Elapsed time = 10.617004156112671
[]
LC08_L1TP_040037_20180707_20180707_01_RT_window_5_6.jpeg
Elapsed time = 10.020596981048584
[]
LC08_L1TP_040037_20180707_20180707_01_RT_window_5_7.jpeg
Elapsed time = 10.177308320999146
[('Fire', 99.6494710445404), ('Fire', 99.5098888874054)]
LC08_L1TP_040037_20180707_20180707_01_RT_window_5_8.jpeg
Elapsed time = 10.1217942237854
[('Fire', 99.68722462654114), ('Fire', 99.52066540718079)]
LC08_L1TP_040037_20180707_20180707_01_RT_window_5_9.jpeg
Elapsed time = 10.344312906265259
[('Smoke', 90.48281908035278)]
LC08_L1TP_040037_20180707_20180707_01_RT_window_6_1.jpeg
Elapsed time = 10.212378978729248
[]
LC08_L1TP_040037_20180707_20180707_01_RT_window_6_10.jpeg
Elapsed time = 9.976900100708008
[]
LC08_L1TP_040037_20180707_20180707_01_RT_window_6_11.jpeg
Elapsed time = 9.905409097671509
[]
LC08_L1TP_040037_20180707_20180707_01_RT_window_6_12.jpeg
Elapsed time = 10

In [7]:
!python3 train_frcnn.py -o simple -p annotate.txt


Using TensorFlow backend.
/Users/shalu/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/shalu/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/shalu/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/shalu/anaconda3/lib/python3.7/site-packages/tenso

W0512 23:13:49.817363 4429276608 deprecation_wrapper.py:119] From /Users/shalu/anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:3661: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.

W0512 23:13:51.460566 4429276608 deprecation_wrapper.py:119] From /Users/shalu/anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:3814: The name tf.random_normal is deprecated. Please use tf.random.normal instead.

W0512 23:13:51.515862 4429276608 deprecation_wrapper.py:119] From /Users/shalu/Documents/ML-Research/data/keras-frcnn/keras_frcnn/RoiPoolingConv.py:105: The name tf.image.resize_images is deprecated. Please use tf.image.resize instead.

W0512 23:13:52.643643 4429276608 deprecation_wrapper.py:119] From /Users/shalu/anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:3665: The name tf.nn.avg_pool is deprecated. Please use tf.nn.avg_pool2d instead.

loading weights from resnet50_weights_tf_dim_ordering

38/50 [=====================>........] - ETA: 2:11 - rpn_cls: 3.8657 - rpn_regr: 1.3047 - detector_cls: 0.4680 - detector_regr: 0.0660Hello
Average number of overlapping bounding boxes from RPN = 0.28 for 50 previous iterations
Before data generation
Before data generation
39/50 [======================>.......] - ETA: 2:01 - rpn_cls: 3.7756 - rpn_regr: 1.2968 - detector_cls: 0.4561 - detector_regr: 0.0643Before data generation
Before data generation
43/50 [========================>.....] - ETA: 1:16 - rpn_cls: 3.6163 - rpn_regr: 1.2784 - detector_cls: 0.4194 - detector_regr: 0.0694Before data generation
Before data generation
48/50 [===========================>..] - ETA: 21s - rpn_cls: 3.4918 - rpn_regr: 1.2646 - detector_cls: 0.3851 - detector_regr: 0.0802Before data generation
Before data generation
Before data generation
50/50 [==============================] - 546s 11s/step - rpn_cls: 3.4214 - rpn_regr: 1.2470 - detector_cls: 0.3726 - detector_regr: 0.0837
Mean number of bounding b

50/50 [==============================] - 446s 9s/step - rpn_cls: 1.4176 - rpn_regr: 1.1936 - detector_cls: 0.0850 - detector_regr: 0.0994
Mean number of bounding boxes from RPN overlapping ground truth boxes: 1.0192307692307692
Classifier accuracy for bounding boxes from RPN: 0.966875
Loss RPN classifier: 1.4176093201711775
Loss RPN regression: 1.193625545501709
Loss Detector classifier: 0.0850447041840198
Loss Detector regression: 0.09937755852937698
Elapsed time: 471.5094382762909
Total loss decreased from 5.12476544514815 to 2.7956571283862837, saving weights
Epoch 3/50
Before data generation
31/50 [=================>............] - ETA: 2:51 - rpn_cls: 1.0660 - rpn_regr: 1.0658 - detector_cls: 0.0774 - detector_regr: 0.1358Hello
Average number of overlapping bounding boxes from RPN = 1.14 for 50 previous iterations
Before data generation
33/50 [==================>...........] - ETA: 2:36 - rpn_cls: 1.0485 - rpn_regr: 1.0501 - detector_cls: 0.0805 - detector_regr: 0.1314Before data 

50/50 [==============================] - 488s 10s/step - rpn_cls: 0.8687 - rpn_regr: 1.0173 - detector_cls: 0.0850 - detector_regr: 0.1172
Mean number of bounding boxes from RPN overlapping ground truth boxes: 1.08
Classifier accuracy for bounding boxes from RPN: 0.9675
Loss RPN classifier: 0.8687453261017799
Loss RPN regression: 1.0173124694824218
Loss Detector classifier: 0.08503413030171941
Loss Detector regression: 0.11723802998661995
Elapsed time: 489.2425158023834
Total loss decreased from 2.7956571283862837 to 2.088329955872541, saving weights
Epoch 4/50
Before data generation
31/50 [=================>............] - ETA: 3:25 - rpn_cls: 0.1216 - rpn_regr: 0.7966 - detector_cls: 0.1246 - detector_regr: 0.1508Hello
Average number of overlapping bounding boxes from RPN = 1.84 for 50 previous iterations
Before data generation
32/50 [==================>...........] - ETA: 3:14 - rpn_cls: 0.1197 - rpn_regr: 0.7991 - detector_cls: 0.1210 - detector_regr: 0.1461Before data generation


50/50 [==============================] - 543s 11s/step - rpn_cls: 0.1767 - rpn_regr: 0.7632 - detector_cls: 0.1305 - detector_regr: 0.1745
Mean number of bounding boxes from RPN overlapping ground truth boxes: 2.12
Classifier accuracy for bounding boxes from RPN: 0.946875
Loss RPN classifier: 0.17669672423973679
Loss RPN regression: 0.7632025191187859
Loss Detector classifier: 0.1305440794110473
Loss Detector regression: 0.17448528411798178
Elapsed time: 543.547455072403
Total loss decreased from 2.088329955872541 to 1.2449286068875518, saving weights
Epoch 5/50
Before data generation
31/50 [=================>............] - ETA: 3:19 - rpn_cls: 0.0882 - rpn_regr: 0.5491 - detector_cls: 0.1709 - detector_regr: 0.2307Hello
Average number of overlapping bounding boxes from RPN = 2.54 for 50 previous iterations
Before data generation


50/50 [==============================] - 525s 10s/step - rpn_cls: 0.0879 - rpn_regr: 0.5259 - detector_cls: 0.1835 - detector_regr: 0.3065
Mean number of bounding boxes from RPN overlapping ground truth boxes: 3.16
Classifier accuracy for bounding boxes from RPN: 0.93875
Loss RPN classifier: 0.08785882856696844
Loss RPN regression: 0.5258966055512428
Loss Detector classifier: 0.1835124895973422
Loss Detector regression: 0.3064676174521446
Elapsed time: 525.9400403499603
Total loss decreased from 1.2449286068875518 to 1.1037355411676981, saving weights
Epoch 6/50
Before data generation
31/50 [=================>............] - ETA: 3:21 - rpn_cls: 0.1634 - rpn_regr: 0.3557 - detector_cls: 0.1585 - detector_regr: 0.2836Hello
Average number of overlapping bounding boxes from RPN = 4.02 for 50 previous iterations
Before data generation


50/50 [==============================] - 527s 11s/step - rpn_cls: 0.1324 - rpn_regr: 0.3279 - detector_cls: 0.1760 - detector_regr: 0.2722
Mean number of bounding boxes from RPN overlapping ground truth boxes: 4.14
Classifier accuracy for bounding boxes from RPN: 0.934375
Loss RPN classifier: 0.132372801695019
Loss RPN regression: 0.3279365745186806
Loss Detector classifier: 0.17595630027353765
Loss Detector regression: 0.272185868024826
Elapsed time: 527.8341958522797
Total loss decreased from 1.1037355411676981 to 0.9084515445120632, saving weights
Epoch 7/50
Before data generation
31/50 [=================>............] - ETA: 3:26 - rpn_cls: 0.0632 - rpn_regr: 0.2438 - detector_cls: 0.2833 - detector_regr: 0.2071Hello
Average number of overlapping bounding boxes from RPN = 4.12 for 50 previous iterations
Before data generation


50/50 [==============================] - 541s 11s/step - rpn_cls: 0.0857 - rpn_regr: 0.2214 - detector_cls: 0.2459 - detector_regr: 0.1856
Mean number of bounding boxes from RPN overlapping ground truth boxes: 4.38
Classifier accuracy for bounding boxes from RPN: 0.933125
Loss RPN classifier: 0.08566633756272495
Loss RPN regression: 0.22142535895109178
Loss Detector classifier: 0.24592244654893874
Loss Detector regression: 0.185593196246773
Elapsed time: 542.6328330039978
Total loss decreased from 0.9084515445120632 to 0.7386073393095285, saving weights
Epoch 8/50
Before data generation
31/50 [=================>............] - ETA: 3:32 - rpn_cls: 0.0433 - rpn_regr: 0.1765 - detector_cls: 0.1376 - detector_regr: 0.1174Hello
Average number of overlapping bounding boxes from RPN = 4.1 for 50 previous iterations
Before data generation


50/50 [==============================] - 556s 11s/step - rpn_cls: 0.0539 - rpn_regr: 0.1682 - detector_cls: 0.1261 - detector_regr: 0.1103
Mean number of bounding boxes from RPN overlapping ground truth boxes: 3.62
Classifier accuracy for bounding boxes from RPN: 0.9525
Loss RPN classifier: 0.05386593190021813
Loss RPN regression: 0.1681947311758995
Loss Detector classifier: 0.12614615514874458
Loss Detector regression: 0.110282961956691
Elapsed time: 556.464124917984
Total loss decreased from 0.7386073393095285 to 0.45848978018155323, saving weights
Epoch 9/50
Before data generation
31/50 [=================>............] - ETA: 3:15 - rpn_cls: 0.0226 - rpn_regr: 0.1375 - detector_cls: 0.0633 - detector_regr: 0.0462Hello
Average number of overlapping bounding boxes from RPN = 3.56 for 50 previous iterations
Before data generation


50/50 [==============================] - 516s 10s/step - rpn_cls: 0.0194 - rpn_regr: 0.1247 - detector_cls: 0.0564 - detector_regr: 0.0453
Mean number of bounding boxes from RPN overlapping ground truth boxes: 3.66
Classifier accuracy for bounding boxes from RPN: 0.981875
Loss RPN classifier: 0.019442876318935307
Loss RPN regression: 0.12470185803249478
Loss Detector classifier: 0.05640893097966909
Loss Detector regression: 0.045258340165019034
Elapsed time: 517.587167263031
Total loss decreased from 0.45848978018155323 to 0.24581200549611823, saving weights
Epoch 10/50
Before data generation
31/50 [=================>............] - ETA: 3:25 - rpn_cls: 0.0182 - rpn_regr: 0.1098 - detector_cls: 0.0267 - detector_regr: 0.0081Hello
Average number of overlapping bounding boxes from RPN = 3.86 for 50 previous iterations
Before data generation


50/50 [==============================] - 540s 11s/step - rpn_cls: 0.0136 - rpn_regr: 0.1064 - detector_cls: 0.0385 - detector_regr: 0.0100
Mean number of bounding boxes from RPN overlapping ground truth boxes: 3.92
Classifier accuracy for bounding boxes from RPN: 0.99
Loss RPN classifier: 0.013592841406352817
Loss RPN regression: 0.1064335906971246
Loss Detector classifier: 0.038534380975179375
Loss Detector regression: 0.010016228640961345
Elapsed time: 541.4309160709381
Total loss decreased from 0.24581200549611823 to 0.16857704171961815, saving weights
Epoch 11/50
Before data generation
31/50 [=================>............] - ETA: 3:23 - rpn_cls: 0.0057 - rpn_regr: 0.0812 - detector_cls: 0.0790 - detector_regr: 0.0741Hello
Average number of overlapping bounding boxes from RPN = 3.8 for 50 previous iterations
Before data generation


50/50 [==============================] - 529s 11s/step - rpn_cls: 0.0195 - rpn_regr: 0.0885 - detector_cls: 0.0871 - detector_regr: 0.0797
Mean number of bounding boxes from RPN overlapping ground truth boxes: 4.0
Classifier accuracy for bounding boxes from RPN: 0.970625
Loss RPN classifier: 0.019545815747696905
Loss RPN regression: 0.08848695004358888
Loss Detector classifier: 0.08705081562511623
Loss Detector regression: 0.0796832048559736
Elapsed time: 530.7738649845123
Epoch 12/50
Before data generation
31/50 [=================>............] - ETA: 3:14 - rpn_cls: 0.0363 - rpn_regr: 0.0664 - detector_cls: 0.0292 - detector_regr: 0.0453Hello
Average number of overlapping bounding boxes from RPN = 4.74 for 50 previous iterations
Before data generation


50/50 [==============================] - 503s 10s/step - rpn_cls: 0.0333 - rpn_regr: 0.0671 - detector_cls: 0.0375 - detector_regr: 0.0461
Mean number of bounding boxes from RPN overlapping ground truth boxes: 4.68
Classifier accuracy for bounding boxes from RPN: 0.99125
Loss RPN classifier: 0.03333707065321505
Loss RPN regression: 0.06710196970030666
Loss Detector classifier: 0.03745001445524394
Loss Detector regression: 0.046119006103836
Elapsed time: 502.60380482673645
Epoch 13/50
Before data generation
31/50 [=================>............] - ETA: 3:21 - rpn_cls: 0.0108 - rpn_regr: 0.0563 - detector_cls: 0.0808 - detector_regr: 0.0308Hello
Average number of overlapping bounding boxes from RPN = 4.18 for 50 previous iterations
Before data generation


50/50 [==============================] - 528s 11s/step - rpn_cls: 0.0103 - rpn_regr: 0.0513 - detector_cls: 0.1110 - detector_regr: 0.0342
Mean number of bounding boxes from RPN overlapping ground truth boxes: 4.14
Classifier accuracy for bounding boxes from RPN: 0.9825
Loss RPN classifier: 0.010277859135530889
Loss RPN regression: 0.05130566654494032
Loss Detector classifier: 0.1109888499439694
Loss Detector regression: 0.03424759539940169
Elapsed time: 527.6566362380981
Epoch 14/50
Before data generation
 2/50 [>.............................] - ETA: 7:33 - rpn_cls: 0.0232 - rpn_regr: 0.0963 - detector_cls: 0.1733 - detector_regr: 0.0173Before data generation
^C


In [8]:
!python3 /Users/shalu/Documents/ML-Research/data/keras-frcnn/test_frcnn.py -p /Users/shalu/Documents/ML-Research/data/keras-frcnn/test_images

Using TensorFlow backend.
/Users/shalu/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/shalu/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/shalu/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/shalu/anaconda3/lib/python3.7/site-packages/tenso

In [10]:
!python3 /Users/shalu/Documents/ML-Research/data/keras-frcnn/test_frcnn.py -p /Users/shalu/Documents/ML-Research/data/keras-frcnn/test_images

Using TensorFlow backend.
/Users/shalu/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/shalu/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/shalu/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/shalu/anaconda3/lib/python3.7/site-packages/tenso